# Pipeline configuration
---
workspace:
  base: /app
  path: code

pipeline:
# Build project
  build:
  # Build image to use
    image: mcr.microsoft.com/dotnet/sdk:5.0
    # Commands to run 
    commands:
      - dotnet clean
      - dotnet build --configuration ${DOTNET_CONFIGURATION=Release}
    # Step while excluding [deployment]
    when:
      event:
        exclude: [deployment]
